//============================================================================
// Copyright (c) 2026 Qualcomm Innovation Center, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//============================================================================

package com.qualcomm.qidk.vlm;

/**
 * Message types for the VLM chat RecyclerView.
 */
public enum MessageType {
    /** Message sent by the user (text only or text + image). */
    USER,
    /** Message generated by the VLM assistant. */
    ASSISTANT
}
